### ISSUE TITLE
关于组织的维护

### ISSUE THREAD

**Issue by Memorywzd** [bljx/BFU-leaf#12]
前辈们好，我是2021届计协的会长（memorywzd@bjfu.edu.cn）协会在带领同学们做线上维修等网站、小程序项目，希望征求前辈们的意见把这个账号继承下来继续更新在此。希望与负责人取得联系。

**Comment by Memorywzd** [comment]
https://github.com/bljx2021project

**Comment by cyyzero** [comment]
收到👍邀请你进组织了哈

**Comment by d100972** [comment]
加油！
线上程序终究解决的是“待就医者” 与 我们计协之间信息传输的效率问题，而我们计协真正要做的还是帮助“患者”恢复健康，这需要过硬的技术与志愿者精神，劳累在所难免，希望你们能坚持住。
另外，线上交流较于面对面交流，多了一层 文字层 的抽象，而每多加一层抽象，就会丢失一部分细节，这个细节就是面对面与患者家属沟通时话语腔调里的感情，眼神中的真诚，自信的操作带给患者家属的靠谱与平静， 让患者家属感受到无感情的文字的“冰冷”在所难免，所以答复患者家属的话语一定要有足够的人文关怀，体现出技术人的温度~ 
薪火相传，很高兴新一代的伙伴继续传递技术人的温度，向你们致敬！

**Comment by Xayah-Hina** [comment]
加油哦～ (っ ̯ -｡)👍

**Comment by Memorywzd** [comment]
谢谢前辈们的鼓励，没想到这么快就收到回复了！协会目前在大家的努力下有一百余名来自各个学院的会员，每学期承办常规维修活动十余次，大型维修日一到两次，最近一次大型维修日单日解决200多人次电脑问题，相信协会会在大家的鼓励下一直走下去越办越好！
