### ISSUE TITLE
18级的来占个楼

### ISSUE THREAD

**Issue by Formoterol** [bljx/BFU-leaf#9]
开学了打算把这学期几门课的代码开源，然后就逛到这了，有一说一这个确实应该继续做下去，不少计科的课程确实不错的。

**Comment by cyyzero** [comment]
可以的，欢迎提pr~

**Comment by Formoterol** [comment]
> 可以的，欢迎提pr~

话说你们还打算维护吗，而且我是不是得叫一声学长学姐hhh

**Comment by cyyzero** [comment]
> 
> 
> > 可以的，欢迎提pr~
> 
> 话说你们还打算维护吗，而且我是不是得叫一声学长学姐hhh

我是16级的学长。这个项目还在维护的哈，提pr的话我会merge。

**Comment by Formoterol** [comment]
> > > 可以的，欢迎提pr~
> > 
> > 
> > 话说你们还打算维护吗，而且我是不是得叫一声学长学姐hhh
> 
> 我是16级的学长。这个项目还在维护的哈，提pr的话我会merge。

好的学长，明天我整理一下，看看有啥可以提交的，QAQ。

**Comment by recessburton** [comment]
11级的表示：太强了！！！可惜毕业了。早看到的话，门门90分！
